os:
  - linux
  - osx
  
language: cpp
compiler: gcc
sudo: false
addons:
  apt:
    packages:
      - liblog4cxx10-dev 
      - libboost-program-options-dev 
    - libboost-filesystem-dev
    - libboost-date-time-dev
    - libboost-system-dev
    - libboost-test-dev
    - libboost-thread-dev
    - libzmq3-dev
env:
- PYTHONPATH=./lib/python
install:
- pwd
- ls *
- mkdir -p build
- cd build
- cmake ..
- make VERBOSE=1
- pip install --user -r $PYTHONPATH/requirements.txt
script:
- pwd
- ls *
- bin/frameReceiverTest --log_level=all
- python --version
- python bin/run_integration_test.py --frames=1 --interval=1.0 --timeout=30
#notifications:
#  slack:
#    secure: r8pM4/MZxsJrazTV/mm6WF/qUb+Kz6rOnmNtCS3ggHthH4ISkks9hGGY055cOG3F0AUBzLimPttYFwAn9uPLxTr2VCWUZ9Bx5q4CAILspmzYTJcbFDG+vyiyJEw5b2DzaXto9wcvRMNx5UDGlXXygEvBwpEV7Mgh2jR9jEQKGds=
