language: cpp
sudo: false
  
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages: ['liblog4cxx10-dev','libboost-program-options-dev','libboost-filesystem-dev','libboost-date-time-dev','libboost-system-dev','libboost-test-dev','libboost-thread-dev','libzmq3-dev']

    - os: osx
      osx_image: xcode7
      compiler: clang
      before_install: brew update && brew install cmake log4cxx boost zeromq

env:
  - PYTHONPATH=./lib/python

install:
  - mkdir -p build
  - cd build
  - cmake ..
  - make VERBOSE=1
  - pip install --user -r $PYTHONPATH/requirements.txt

script:
  - bin/frameReceiverTest --log_level=all
  - python bin/run_integration_test.py --frames=1 --interval=1.0 --timeout=30
